### ISSUE TITLE
Useful samples

### ISSUE THREAD

**Issue by manikantag** [zenvers/cron#1]
Hi, very useful tool.

It would be more helpful if there are some common patterns like 

- Everyday at 2 am
- Every Saturday at 5 am
- Every month end
- Every 3 days

I think you got the idea. What do you say? 
Thanks

**Comment by screfy** [comment]
Sorry for late response, this is not possible right now, because we are using [cronstrue](https://www.npmjs.com/package/cronstrue) package with default locale for this.

**Comment by manikantag** [comment]
I think you misunderstood my question. My suggestion is about adding some example patterns in the website. Now I see some examples.
